# Generated by Django 5.2 on 2025-06-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
