# Generated by Django 5.1.6 on 2025-05-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0003_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='hi', max_length=255),
            preserve_default=False,
        ),
    ]
