# Generated by Django 5.2 on 2025-05-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0005_user_address_user_date_of_birth_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
