# Generated by Django 5.2 on 2025-04-06 08:54

import school.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_academicyear_id_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='id',
            field=models.CharField(default=school.models.generate_custom_uuid, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.CharField(default=school.models.generate_custom_uuid, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.CharField(default=school.models.generate_custom_uuid, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.CharField(default=school.models.generate_custom_uuid, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='id',
            field=models.CharField(default=school.models.generate_custom_uuid, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.CharField(default=school.models.generate_custom_uuid, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default=school.models.generate_custom_uuid, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.CharField(default=school.models.generate_custom_uuid, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.CharField(default=school.models.generate_custom_uuid, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
