# Generated by Django 5.2 on 2025-04-13 05:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_class_class_teacher_class_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='school.subject'),
        ),
    ]
