# Generated by Django 5.1.6 on 2025-05-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_class_options_class_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='general_password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
