# Generated by Django 5.1.6 on 2025-05-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_class_options_class_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
    ]
