# Generated by Django 5.1.6 on 2025-05-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
